/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

import static HotelReservationSystem.Loginform.userobj;
import com.sun.org.apache.bcel.internal.generic.AALOAD;

/**
 *
 * @author thath
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_roomReservation = new javax.swing.JButton();
        btn_hallReservation = new javax.swing.JButton();
        btn_reservationdetails = new javax.swing.JButton();
        btn_customerProfile = new javax.swing.JButton();
        btn_roomDisplay = new javax.swing.JButton();
        btn_feedback = new javax.swing.JButton();
        btn_hallDetails = new javax.swing.JButton();
        btn_hallReservation2 = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1110, 650));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1110, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_roomReservation.setBackground(new java.awt.Color(246, 230, 134));
        btn_roomReservation.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_roomReservation.setText("Room Reservation");
        btn_roomReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomReservationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_roomReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, 60));

        btn_hallReservation.setBackground(new java.awt.Color(246, 230, 134));
        btn_hallReservation.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_hallReservation.setText("Hall Reservation");
        btn_hallReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hallReservationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hallReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 220, 60));

        btn_reservationdetails.setBackground(new java.awt.Color(246, 230, 134));
        btn_reservationdetails.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_reservationdetails.setText("Reservation details");
        btn_reservationdetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reservationdetails.setPreferredSize(new java.awt.Dimension(172, 30));
        btn_reservationdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservationdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reservationdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, 60));

        btn_customerProfile.setBackground(new java.awt.Color(246, 230, 134));
        btn_customerProfile.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_customerProfile.setForeground(new java.awt.Color(0, 0, 0));
        btn_customerProfile.setText("Customer Profile");
        btn_customerProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_customerProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 420, 60));

        btn_roomDisplay.setBackground(new java.awt.Color(246, 230, 134));
        btn_roomDisplay.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_roomDisplay.setText("Room details view");
        btn_roomDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btn_roomDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 220, 60));

        btn_feedback.setBackground(new java.awt.Color(246, 230, 134));
        btn_feedback.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_feedback.setForeground(new java.awt.Color(0, 0, 0));
        btn_feedback.setText("Customer FeedBacks");
        btn_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feedbackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 220, 60));

        btn_hallDetails.setBackground(new java.awt.Color(246, 230, 134));
        btn_hallDetails.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_hallDetails.setText("Hall details View");
        btn_hallDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hallDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hallDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 220, 60));

        btn_hallReservation2.setBackground(new java.awt.Color(246, 230, 134));
        btn_hallReservation2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_hallReservation2.setText("Hall Reservation details");
        btn_hallReservation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hallReservation2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hallReservation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 220, 60));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(0, 0, 0));
        btn_logout.setText("LogOut");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 220, 60));

        btn_exit.setBackground(new java.awt.Color(246, 230, 134));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(0, 0, 0));
        btn_exit.setText("X");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_roomReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomReservationActionPerformed
       Loginform.reservationObj.show();
    }//GEN-LAST:event_btn_roomReservationActionPerformed

    private void btn_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feedbackActionPerformed
      Loginform.FeedbackObj.show();
      Loginform.FeedbackObj.setData();
             
    }//GEN-LAST:event_btn_feedbackActionPerformed

    private void btn_customerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerProfileActionPerformed
      userobj.show();
        
    }//GEN-LAST:event_btn_customerProfileActionPerformed

    private void btn_hallReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hallReservationActionPerformed
        Loginform.hallReservation.show();
    }//GEN-LAST:event_btn_hallReservationActionPerformed

    private void btn_reservationdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservationdetailsActionPerformed
       Loginform.reservationDetails.show();
       Loginform.reservationDetails.setData();
    }//GEN-LAST:event_btn_reservationdetailsActionPerformed

    private void btn_roomDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomDisplayActionPerformed
       RoomDisplay obj = new RoomDisplay();
       obj.show();
    }//GEN-LAST:event_btn_roomDisplayActionPerformed

    private void btn_hallReservation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hallReservation2ActionPerformed
       Loginform.HallreservationDetails.show();
       Loginform.HallreservationDetails.setData();
    }//GEN-LAST:event_btn_hallReservation2ActionPerformed

    private void btn_hallDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hallDetailsActionPerformed
       HallDetails obj = new HallDetails();
        obj.show();
    }//GEN-LAST:event_btn_hallDetailsActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
     this.dispose();
     Loginform obj = new Loginform();
     obj.show();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_customerProfile;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_feedback;
    private javax.swing.JButton btn_hallDetails;
    private javax.swing.JButton btn_hallReservation;
    private javax.swing.JButton btn_hallReservation2;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_reservationdetails;
    private javax.swing.JButton btn_roomDisplay;
    private javax.swing.JButton btn_roomReservation;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
