/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author thath
 */
public class FeedbackSubmit extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackDisplay
     */
    public FeedbackSubmit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_cmmnt = new javax.swing.JTextArea();
        txt_cusname = new javax.swing.JTextField();
        txt_subject = new javax.swing.JTextField();
        btn_bck = new javax.swing.JButton();
        btn_viewFeedback = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 156, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 74, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Comment");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 93, -1));

        txt_cmmnt.setColumns(20);
        txt_cmmnt.setRows(5);
        jScrollPane1.setViewportView(txt_cmmnt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 430, 170));

        txt_cusname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cusnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 278, -1));

        txt_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subjectActionPerformed(evt);
            }
        });
        getContentPane().add(txt_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 280, -1));

        btn_bck.setBackground(new java.awt.Color(255, 255, 255));
        btn_bck.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_bck.setText("Back");
        btn_bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bckActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 160, 40));

        btn_viewFeedback.setBackground(new java.awt.Color(246, 230, 134));
        btn_viewFeedback.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_viewFeedback.setText("View Feedback");
        btn_viewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewFeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 160, 40));

        btn_submit.setBackground(new java.awt.Color(246, 230, 134));
        btn_submit.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/give us a feedback.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cusnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cusnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cusnameActionPerformed

    private void txt_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subjectActionPerformed

    private void btn_bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bckActionPerformed
        this.hide();
    }//GEN-LAST:event_btn_bckActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed

        String cusname, email, subject, comment;

        cusname = txt_cusname.getText();
        subject = txt_subject.getText();
        comment = txt_cmmnt.getText();

        if (cusname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name cannot be empty ", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (subject.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Subject cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (comment.isEmpty()) {
            JOptionPane.showMessageDialog(null, "comment cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Statement st = HotelReservationSystem.DBConnection.creatConnection().createStatement();
                String query = "INSERT INTO `feedback` ( `customerID`, `customerName`, `subject`, `comment`) VALUES ('" + UserID + "', '" + cusname + "', '" + subject + "', '" + comment + "');";
                int count = st.executeUpdate(query);

                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Comment submitted !!.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    clearData();

                }

            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_viewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewFeedbackActionPerformed
        Loginform.feedbackDisplay.show();
        Loginform.feedbackDisplay.setData(UserID);
    }//GEN-LAST:event_btn_viewFeedbackActionPerformed

    public void clearData() {
        txt_cusname.setText(null);
        txt_cmmnt.setText(null);
        txt_subject.setText(null);
    }

    public void setData() {
        txt_cusname.setText(name);
    }
    String UserID, name;

    public void setUserData(String UID, String name) {
        this.UserID = UID;
        this.name = name;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackSubmit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bck;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_viewFeedback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_cmmnt;
    private javax.swing.JTextField txt_cusname;
    private javax.swing.JTextField txt_subject;
    // End of variables declaration//GEN-END:variables
}
