/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author thath
 */
public class FeedBack extends javax.swing.JFrame {

    /**
     * Creates new form FeedBack
     */
    public FeedBack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_feedbackdetails = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_subject = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_cmmnt = new javax.swing.JTextArea();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_update.setBackground(new java.awt.Color(246, 230, 134));
        btn_update.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 160, 40));

        tbl_feedbackdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Feedback ID", "CustomerID", "Customer Name", "Subject", "Comment"
            }
        ));
        tbl_feedbackdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_feedbackdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_feedbackdetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 600, 360));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 74, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Comment");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 93, -1));

        txt_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subjectActionPerformed(evt);
            }
        });
        getContentPane().add(txt_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 310, -1));

        btn_delete.setBackground(new java.awt.Color(246, 230, 134));
        btn_delete.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 160, 40));

        txt_cmmnt.setColumns(20);
        txt_cmmnt.setRows(5);
        jScrollPane2.setViewportView(txt_cmmnt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 310, 310));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/my feedbacks.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String subject, comment, feedid;

        subject = txt_subject.getText();
        comment = txt_cmmnt.getText();
        feedid = feedbackId;

        if (subject.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Subject cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (comment.isEmpty()) {
            JOptionPane.showMessageDialog(null, "comment cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                Statement st = HotelReservationSystem.DBConnection.creatConnection().createStatement();
                String query = "UPDATE `feedback` SET `subject` = '" + subject + "', `comment` = '" + comment + "' WHERE `feedback`.`feedback_id` = '" + feedid + "';";
                int count = st.executeUpdate(query);
                System.out.println(query);
                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Comment update successfull.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    setData(cusNo);
                    clearData();

                }

                tbl_feedbackdetails.clearSelection();

            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_btn_updateActionPerformed

    public void clearData() {

        txt_cmmnt.setText(null);
        txt_subject.setText(null);
    }
    String feedbackId;
    private void tbl_feedbackdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_feedbackdetailsMouseClicked
        int selectedRow = tbl_feedbackdetails.getSelectedRow();
        TableModel model = tbl_feedbackdetails.getModel();

        txt_subject.setText(model.getValueAt(selectedRow, 3).toString());
        txt_cmmnt.setText(model.getValueAt(selectedRow, 4).toString());
        feedbackId = model.getValueAt(selectedRow, 0).toString();


    }//GEN-LAST:event_tbl_feedbackdetailsMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subjectActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        String subject, comment, feedid;

        subject = txt_subject.getText();
        comment = txt_cmmnt.getText();
        feedid = feedbackId;

        if (subject.isEmpty() ||comment.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Select the feedback first", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                Statement st = HotelReservationSystem.DBConnection.creatConnection().createStatement();
                String query = "DELETE FROM `feedback` WHERE `feedback`.`feedback_id` = '" + feedbackId + "';";
                int count = st.executeUpdate(query);
                //System.out.println(query);
                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Reservation delete successfull.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    setData(cusNo);
                    clearData();

                }

                tbl_feedbackdetails.clearSelection();

            } catch (Exception e) {
            }
        }


    }//GEN-LAST:event_btn_deleteActionPerformed

    String cusNo;

    public void setData(String cusID) {
        DBConnection obj = new DBConnection();
        ResultSet rst = obj.getFeedbackDetails(cusID);
        DefaultTableModel s = (DefaultTableModel) tbl_feedbackdetails.getModel();
        s.setNumRows(0);

        this.cusNo = cusID;

        try {
            while (rst.next()) {

                String feedbackId = rst.getString("feedback_id");
                String customerID = rst.getString("customerID");
                String customerName = rst.getString("customerName");
                String subject = rst.getString("subject");
                String comment = rst.getString("comment");

                String data[] = {feedbackId, customerID, customerName, subject, comment};

                s.addRow(data);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservationdetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedBack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_feedbackdetails;
    private javax.swing.JTextArea txt_cmmnt;
    private javax.swing.JTextField txt_subject;
    // End of variables declaration//GEN-END:variables
}
