/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chamod
 */
public class HallDetails extends javax.swing.JFrame {

    /**
     * Creates new form HallDetails
     */
    public HallDetails() {
        initComponents();
        setHallData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_halldetails = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_capacity = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_halldetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall Id", "Hall name", "Seating capacity", "dinning", "air condition", "Availability"
            }
        ));
        tbl_halldetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_halldetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_halldetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 1040, 310));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 160, 40));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search from seating capacity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txt_capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_capacityActionPerformed(evt);
            }
        });
        getContentPane().add(txt_capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 250, -1));

        btn_search.setBackground(new java.awt.Color(246, 230, 134));
        btn_search.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hall details.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_halldetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_halldetailsMouseClicked
       
    }//GEN-LAST:event_tbl_halldetailsMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_capacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_capacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_capacityActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       DBConnection obj = new DBConnection();
       int seats = Integer.parseInt(txt_capacity.getText());
        ResultSet rst = obj.getHallDataFromSeatCapacity(seats);
        DefaultTableModel s = (DefaultTableModel) tbl_halldetails.getModel();
         s.setNumRows(0);

        try {
            while (rst.next()) {

                String hallId = rst.getString("hallID");
                String hallname = rst.getString("hall_name");
                String seating = rst.getString("seating_capacity");
                String dinning = rst.getString("dinning");
                String airCondition = rst.getString("air_condition");
                String status = rst.getString("status");
              

                String data[] = {hallId, hallname, seating, dinning, airCondition, status};

                
                s.addRow(data);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservationdetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_searchActionPerformed

    public void setHallData(){
    
        DBConnection obj = new DBConnection();
        ResultSet rst = obj.getHallData();

        try {
            while (rst.next()) {

                String hallId = rst.getString("hallID");
                String hallname = rst.getString("hall_name");
                String seating = rst.getString("seating_capacity");
                String dinning = rst.getString("dinning");
                String airCondition = rst.getString("air_condition");
                String status = rst.getString("status");
              

                String data[] = {hallId, hallname, seating, dinning, airCondition, status};

                DefaultTableModel s = (DefaultTableModel) tbl_halldetails.getModel();
                s.addRow(data);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservationdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HallDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_halldetails;
    private javax.swing.JTextField txt_capacity;
    // End of variables declaration//GEN-END:variables
}
