/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thath
 */
public class RoomDisplay extends javax.swing.JFrame {

    /**
     * Creates new form RoomDisplay
     */
    public RoomDisplay() {
        initComponents();
        setRoomData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_roomdetails = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_roomprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1110, 650));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1110, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_roomdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Room type", "price", "Bed type", "Air condition", "View", "In room dining", "Room Availibility"
            }
        ));
        tbl_roomdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_roomdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_roomdetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 1040, 300));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 160, 40));

        btn_search.setBackground(new java.awt.Color(246, 230, 134));
        btn_search.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 120, 30));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search from room price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txt_roomprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_roompriceActionPerformed(evt);
            }
        });
        getContentPane().add(txt_roomprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/room details.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_roomdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_roomdetailsMouseClicked

    }//GEN-LAST:event_tbl_roomdetailsMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.hide();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_roompriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roompriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roompriceActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
         DBConnection obj = new DBConnection();
         
         double roomprice = Double.parseDouble(txt_roomprice.getText());
        ResultSet rst = obj.getRoomDataFromprice(roomprice);
        
          DefaultTableModel s = (DefaultTableModel) tbl_roomdetails.getModel();
          s.setNumRows(0);
        

        try {
            while (rst.next()) {

                String roomId = rst.getString("roomID");
                String room_type = rst.getString("room_type");
                String price = rst.getString("price");
                String bedtype = rst.getString("bed_type");
                String air_condition = rst.getString("air_condition");
                String view = rst.getString("view");
                String in_room_dining = rst.getString("in_room_dining");
                String room_status = rst.getString("room_status");

                String data[] = {roomId, room_type, price, bedtype, air_condition, view, in_room_dining, room_status};

              
                s.addRow(data);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservationdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_btn_searchActionPerformed

    public void setRoomData() {
        DBConnection obj = new DBConnection();
        ResultSet rst = obj.getRoomData();
        
        

        try {
            while (rst.next()) {

                String roomId = rst.getString("roomID");
                String room_type = rst.getString("room_type");
                String price = rst.getString("price");
                String bedtype = rst.getString("bed_type");
                String air_condition = rst.getString("air_condition");
                String view = rst.getString("view");
                String in_room_dining = rst.getString("in_room_dining");
                String room_status = rst.getString("room_status");

                String data[] = {roomId, room_type, price, bedtype, air_condition, view, in_room_dining, room_status};

                DefaultTableModel s = (DefaultTableModel) tbl_roomdetails.getModel();
                s.addRow(data);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Reservationdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_roomdetails;
    private javax.swing.JTextField txt_roomprice;
    // End of variables declaration//GEN-END:variables
}
