/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import javafx.beans.binding.Bindings;
import javax.swing.JOptionPane;

/**
 *
 * @author thath
 */
public class RoomReservation extends javax.swing.JFrame {

    /**
     * Creates new form AccommodationInsert
     */
    public RoomReservation() {
        initComponents();
        getRoomId();
        txt_no_of_adults.setText("1");
        txt_no_of_child.setText("1");
        
        datepicker_checkin_date.setDate(Date.from(Instant.now()));
        datepicker_checkout_date.setDate(Date.from(Instant.now()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datepicker_checkout_date = new com.toedter.calendar.JDateChooser();
        datepicker_checkin_date = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txt_no_of_adults = new javax.swing.JTextField();
        txt_no_of_child = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_req = new javax.swing.JTextArea();
        btn_book = new javax.swing.JButton();
        cmb_roomno = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1110, 643));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 80, 22));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Check In Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check Out Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number Of Adults");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Number Of Children");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));
        getContentPane().add(datepicker_checkout_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 270, -1));
        getContentPane().add(datepicker_checkin_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 270, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Special Requests");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        txt_no_of_adults.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_no_of_adultsKeyPressed(evt);
            }
        });
        getContentPane().add(txt_no_of_adults, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 271, -1));

        txt_no_of_child.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_no_of_childKeyPressed(evt);
            }
        });
        getContentPane().add(txt_no_of_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 271, -1));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 160, 40));

        txt_req.setColumns(20);
        txt_req.setRows(5);
        jScrollPane2.setViewportView(txt_req);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 270, -1));

        btn_book.setBackground(new java.awt.Color(246, 230, 134));
        btn_book.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_book.setText("Book");
        btn_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookActionPerformed(evt);
            }
        });
        getContentPane().add(btn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 160, 40));

        getContentPane().add(cmb_roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 270, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reservation.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     String guestID;

    public void setGuestID(String userID) {
        this.guestID = userID;
        //System.out.println(guestID);

    }
    private void btn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookActionPerformed
//        System.out.println(guestID);

        String checkInDate, checkOutDate, requests, roomid;
        int no_adult, no_child;

        requests = txt_req.getText();
        roomid = cmb_roomno.getSelectedItem().toString();

        SimpleDateFormat sfd = new SimpleDateFormat("yyyy-MM-dd");
        checkInDate = sfd.format(datepicker_checkin_date.getDate());
        checkOutDate = sfd.format(datepicker_checkout_date.getDate());

        no_adult = Integer.parseInt(txt_no_of_adults.getText());
        no_child = Integer.parseInt(txt_no_of_child.getText());
        
 

        try {
            Statement st = HotelReservationSystem.DBConnection.creatConnection().createStatement();
            String query = "INSERT INTO `room_reservation` (`roomID`, `guestID`,`check_in_date`, `check_out_date`, `number_of_adults`, `number_of_children`, `special_requests`) VALUES ( '" + roomid + "','" + guestID + "', '" + checkInDate + "', '" + checkOutDate + "', '" + no_adult + "', '" + no_child + "', '" + requests + "');";
            int count = st.executeUpdate(query);
            //System.out.println(query);
            if (count > 0) {
                JOptionPane.showMessageDialog(null, "Reservation successfully completed.", "Success", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong !","Error",JOptionPane.ERROR_MESSAGE);
        }
        


    }//GEN-LAST:event_btn_bookActionPerformed

    public void clear(){
        txt_no_of_adults.setText(null);
        txt_no_of_child.setText(null);
        txt_req.setText(null);
        
        datepicker_checkin_date.setDate(null);
        datepicker_checkout_date.setDate(null);
        
    }
    
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.hide();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_no_of_adultsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_of_adultsKeyPressed
      char c = evt.getKeyChar();
        
        if(Character.isLetter(c))
        {
            txt_no_of_adults.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numbers only","Error",JOptionPane.ERROR_MESSAGE);
            txt_no_of_adults.setEditable(true);
            
        }
    }//GEN-LAST:event_txt_no_of_adultsKeyPressed

    private void txt_no_of_childKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_of_childKeyPressed
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c))
        {
            txt_no_of_child.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numbers only","Error",JOptionPane.ERROR_MESSAGE);
            txt_no_of_child.setEditable(true);
            
        }
    }//GEN-LAST:event_txt_no_of_childKeyPressed

    public void getRoomId() {
        try {
            Statement st = HotelReservationSystem.DBConnection.creatConnection().createStatement();
            ResultSet rst = st.executeQuery("Select * from room_tbl where room_status = 'true'");
            while (rst.next()) {
                cmb_roomno.addItem(rst.getString("roomID"));
            }
        } catch (SQLException ex) {

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_book;
    private javax.swing.JComboBox<String> cmb_roomno;
    private com.toedter.calendar.JDateChooser datepicker_checkin_date;
    private com.toedter.calendar.JDateChooser datepicker_checkout_date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txt_no_of_adults;
    private javax.swing.JTextField txt_no_of_child;
    private javax.swing.JTextArea txt_req;
    // End of variables declaration//GEN-END:variables
}
