/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

/**
 *
 * @author Chamod
 */
public class SplashForm extends javax.swing.JFrame {

    /**
     * Creates new form SplashForm
     */
    public SplashForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loading_bar = new javax.swing.JProgressBar();
        loading_value = new javax.swing.JLabel();
        loading_lable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loading_bar.setBackground(new java.awt.Color(246, 230, 134));
        loading_bar.setForeground(new java.awt.Color(246, 230, 134));
        getContentPane().add(loading_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 394, 730, 10));

        loading_value.setBackground(new java.awt.Color(255, 255, 255));
        loading_value.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loading_value.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(loading_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 80, 30));

        loading_lable.setBackground(new java.awt.Color(255, 255, 255));
        loading_lable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loading_lable.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(loading_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 330, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Splash.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        SplashForm obj = new SplashForm();
        obj.setVisible(true);
        
        
        try {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(100);
                obj.loading_value.setText(i+"%");
                obj.loading_bar.setValue(i);
                
                if(i==10)
                    obj.loading_lable.setText("Turning on modules...");
                if(i==20)
                    obj.loading_lable.setText("Loading modules...");
                if(i==50)
                    obj.loading_lable.setText("Connecting to database...");
                if(i==70)
                    obj.loading_lable.setText("Connection successfull...");
                if(i==80)
                    obj.loading_lable.setText("Lunching application...");
                
                
                
       
            }
            
        obj.dispose();
       
            
            
        } 
        catch (Exception e) {
         
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new SplashForm().setVisible(true);
               Loginform logobj = new Loginform();
               logobj.show();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar loading_bar;
    private javax.swing.JLabel loading_lable;
    private javax.swing.JLabel loading_value;
    // End of variables declaration//GEN-END:variables
}
