/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelReservationSystem;

import static HotelReservationSystem.Loginform.reservationObj;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;

/**
 *
 * @author Chamod
 */
public class UserManageform extends javax.swing.JFrame {

    /**
     * Creates new form UserManageform
     */
    public UserManageform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txt_pass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txt_confpass = new javax.swing.JPasswordField();
        txt_add1 = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        txt_add2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_add3 = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        rbtn_male = new javax.swing.JRadioButton();
        txt_lastname = new javax.swing.JTextField();
        rbtn_female = new javax.swing.JRadioButton();
        txt_firstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pass.setBackground(new java.awt.Color(51, 51, 51));
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 170, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 140, -1));

        txt_confpass.setBackground(new java.awt.Color(51, 51, 51));
        txt_confpass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_confpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 160, -1));

        txt_add1.setBackground(new java.awt.Color(51, 51, 51));
        txt_add1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 170, -1));

        txt_nic.setBackground(new java.awt.Color(51, 51, 51));
        txt_nic.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 170, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 90, -1));

        txt_contact.setBackground(new java.awt.Color(51, 51, 51));
        txt_contact.setForeground(new java.awt.Color(255, 255, 255));
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contactKeyPressed(evt);
            }
        });
        getContentPane().add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 170, -1));

        txt_add2.setBackground(new java.awt.Color(51, 51, 51));
        txt_add2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 170, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 100, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 70, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 100, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 80, -1));

        txt_add3.setBackground(new java.awt.Color(51, 51, 51));
        txt_add3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 180, -1));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 160, 40));

        buttonGroup1.add(rbtn_male);
        rbtn_male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtn_male.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_male.setText("Male");
        getContentPane().add(rbtn_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 80, -1));

        txt_lastname.setBackground(new java.awt.Color(51, 51, 51));
        txt_lastname.setForeground(new java.awt.Color(255, 255, 255));
        txt_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lastnameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 170, -1));

        buttonGroup1.add(rbtn_female);
        rbtn_female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtn_female.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_female.setText("Female");
        rbtn_female.setToolTipText("");
        getContentPane().add(rbtn_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 90, -1));

        txt_firstname.setBackground(new java.awt.Color(51, 51, 51));
        txt_firstname.setForeground(new java.awt.Color(255, 255, 255));
        txt_firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_firstnameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 170, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 170, -1));

        txt_email.setBackground(new java.awt.Color(51, 51, 51));
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 170, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIC");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 60, -1));

        btn_update.setBackground(new java.awt.Color(246, 230, 134));
        btn_update.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 160, 40));

        btn_delete.setBackground(new java.awt.Color(246, 230, 134));
        btn_delete.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 160, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userdetailspage.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        this.hide();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String userId = Loginform.reservationObj.guestID;
        String fname = txt_firstname.getText();
        String lname = txt_lastname.getText();
        String nic = txt_nic.getText();
        String add = txt_add1.getText();
        String add2 = txt_add2.getText();
        String add3 = txt_add3.getText();
        String tele = txt_contact.getText();
        String email = txt_email.getText();
        String password = txt_pass.getText();
        String conf = txt_confpass.getText();

        if (fname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "First name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (lname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Last name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (conf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password is not matching.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (nic.isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIC cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (add.isEmpty() || add2.isEmpty() || add3.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Address  cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (tele.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Telephone cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            if (password.equalsIgnoreCase(conf)) {
                try {
                    Statement st = HotelReservationSystem.DBConnection.creatConnection().createStatement();
                    String query = "UPDATE `customer` SET `first_name` = '" + fname + "', `last_name` = '" + lname + "', `nic` = '" + nic + "', `address` = '" + add + "', `address2` = '" + add2 + "', `address3` = '" + add3 + "', `password` = '" + password + "', `email` = '" + email + "', `telephone` = '" + tele + "' WHERE `customer`.`guest_id` = '" + userId + "';";
                    int count = st.executeUpdate(query);
                    System.out.println(query);
                    if (count > 0) {
                        JOptionPane.showMessageDialog(null, "Profile updated successfully completed.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    }

                } catch (Exception e) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password is not matching.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        String userId = Loginform.reservationObj.guestID;
        try {
            Statement st = HotelReservationSystem.DBConnection.creatConnection().createStatement();
            String query = "delete from customer where guest_id = '" + userId + "'";
            int count = st.executeUpdate(query);
            System.out.println(query);
            if (count > 0) {
                JOptionPane.showMessageDialog(null, "Accont deleted success.", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                Loginform.dashobj.hide();
                Loginform obj = new Loginform();
                obj.show();
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstnameKeyPressed
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c))
        {
            txt_firstname.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter letters only","Error",JOptionPane.ERROR_MESSAGE);
            txt_firstname.setEditable(true);
            
        }
    }//GEN-LAST:event_txt_firstnameKeyPressed

    private void txt_lastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastnameKeyPressed
       char c = evt.getKeyChar();
        
        if(Character.isDigit(c))
        {
            txt_lastname.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter letters only","Error",JOptionPane.ERROR_MESSAGE);
            txt_lastname.setEditable(true);
            
        }
    }//GEN-LAST:event_txt_lastnameKeyPressed

    private void txt_contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyPressed
      char c = evt.getKeyChar();
        
        if(Character.isLetter(c))
        {
            txt_contact.setEditable(false);
            JOptionPane.showMessageDialog(null, "Enter numbers only","Error",JOptionPane.ERROR_MESSAGE);
            txt_contact.setEditable(true);
            
        }
    }//GEN-LAST:event_txt_contactKeyPressed

    public void setData(String user, String pass) {
        DBConnection obj = new DBConnection();
        ResultSet rst = obj.getUserInformation(user, pass);
        try {

            String fname = null, lname = null, nic = null, add = null, add2 = null, add3 = null, gender = null,
                    tele = null, email = null, password = null, userId = null;

            while (rst.next()) {

                userId = rst.getString("guest_id");
                fname = rst.getString("first_name");
                lname = rst.getString("last_name");
                nic = rst.getString("nic");
                add = rst.getString("address");
                add2 = rst.getString("address2");
                add3 = rst.getString("address3");
                gender = rst.getString("gender");
                tele = rst.getString("telephone");
                email = rst.getString("email");
                password = rst.getString("password");
            }
            txt_firstname.setText(fname);
            txt_lastname.setText(lname);
            txt_nic.setText(nic);
            txt_add1.setText(add);
            txt_add2.setText(add2);
            txt_add3.setText(add3);
            txt_contact.setText(tele);
            txt_email.setText(email);
            txt_pass.setText(password);

            if (gender.equalsIgnoreCase("male")) {
                rbtn_male.setSelected(true);
            } else {
                rbtn_female.setSelected(true);
            }

            Loginform.reservationObj.setGuestID(userId);
            Loginform.reservationDetails.setUserID(userId);
            Loginform.hallReservation.setGuestID(userId);
            Loginform.HallreservationDetails.setUserID(userId);
            Loginform.FeedbackObj.setUserData(userId, fname);

        } catch (SQLException ex) {
            Logger.getLogger(UserManageform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManageform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTextField txt_add1;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_add3;
    private javax.swing.JPasswordField txt_confpass;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
